---
title: "Publications"
format:
  html:
    css: dtdd.css
---

Page built: `r format(Sys.time(), "%c")`

```{r}
#| label: set-options
#| echo: false
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)
minCitationsForDisplay = 100

# List of bibtex keys for publications to bring to the top of the list.
# There is no restriction in how many elements this vector can have.
# The order in this vector does matter, as this is what we use to sort among the
# highlighted publications.
top_pubs <- c(
  "AhlmannEltze:NatMeth:2025",
  "AhlmannEltze:NatGen:2025",
  "Lindenhofer:NatMeth:2025",
  "Dehingia:NatCellBio:2025"
)
```

```{r}
#| label: define-formatters
format_bibentry <- function(x) {
  # FIXME: ultimately, this should be turned in a proper bibstyle, registered via `tools::bibstyle()`
  type <- attr(unclass(x), "bibtype")

  journal <- if (type == "Article" && !is.null(x$journal)) {
    paste0("*", unbrace(x$journal), "*")
  } else if (type %in% c("InCollection", "InBook") && !is.null(x$booktitle)) {
    paste0("*", x$booktitle, "*")
  } else if (type == "TechReport" && !is.null(x$institution)) {
    paste0("*", x$institution, "*")
  } else if (!is.null(x$type)) {
    paste0("*", x$type, "*")
  } else if (type == "PhdThesis") {
    "*PhD Thesis*"
  } else {
    ""
  }

  ref <- glue::glue(
    '
    **{ unbrace(x$title) }**, \\
    { x$formatted_authors }. \\
    { journal }, \\
    { x$year } \n
    '
  )

  pdf <- doi <- preprint <- pmc <- citations <- NULL
  if (!is.null(x$pdf) && !is.na(x$pdf)) {
    pdf <- glue::glue('[PDF](https://www.huber.embl.de/pub/pdf/{ x$pdf })')
  }
  if (!is.null(x$doi) && !is.na(x$doi) && !identical(x$doi, "NA")) {
    doi <- glue::glue('[DOI:{ x$doi }](https://doi.org/{ x$doi })')
  }
  if (!is.null(x$preprint) && !is.na(x$preprint)) {
    preprint <- glue::glue('[Preprint](https://doi.org/{ x$doi })')
  }
  if (!is.null(x$epmc) && !is.null(x$epmc)) {
    pmc <- glue::glue('[PMC]({ x$epmc })')
  }

  # Displaying all citations is too noisy so we only do it for "highly cited"
  # papers (with an arbitrary definition of highly cited)
  if (!is.null(x$citations) && !is.na(x$citations) && x$citations >= minCitationsForDisplay) {
    citations <- glue::glue(
      '{ x$citations } citations (source: OpenAlex via openalexR).\n\n'
    )
  }

  links <- glue::glue_collapse(c(pdf, doi, preprint, pmc), sep = " - ")
  glue::glue_collapse(c(ref, citations, links), sep = "<br>")
}

unbrace <- function(string) {
  tools::parseLatex(string) |>
    tools::latexToUtf8() |>
    tools::deparseLatex(dropBraces = TRUE)
}

format_and_highlight <- function(bibentry, group_members) {
  formatted_authors <- glue::glue_collapse(
    format(bibentry$author),
    sep = ", ",
    last = ", and "
  )

  members_when_published <- group_members |>
    dplyr::filter(
      is.na(start_year) | bibentry$year >= start_year,
      is.na(end_year) | bibentry$year <= end_year
    ) |>
    dplyr::pull(group_member)

  for (member in members_when_published) {
    formatted_authors <- gsub(
      paste0("(", member, ")"),
      "[\\1]{.underline}",
      formatted_authors
    )
  }

  formatted_authors <- gsub(
    "\\cocorr",
    "✉",
    formatted_authors,
    fixed = TRUE
  )
  formatted_authors <- gsub(
    "\\cofirst",
    "✷", # not an actual asterisk to avoid markdown issues
    formatted_authors,
    fixed = TRUE
  )

  bibentry$formatted_authors <- formatted_authors

  return(bibentry)
}
```

```{r read-members}
group_members <- readr::read_csv(
  "group_members.csv",
  col_types = "ccc",
  comment = "#"
)
```

```{r read-bib}
publist <- bibtex::read.bib("lop.bib")
```

```{r}
#| label: fetch-citations
#| cache: true
# 1 API request / 50 DOIs
citations <- publist |>
  purrr::map_chr("doi") |>
  openalexR::oa_fetch(doi = _, entity = "works") |>
  dplyr::select(doi, cited_by_count) |>
  dplyr::mutate(doi = gsub("^https://doi.org/", "", doi))
```

```{r}
#| label: render-publications
#| results: asis
#| warning: false
publist <- publist |>
  purrr::map(function(x) {
    if (x$doi %in% citations$doi) {
      x$citations <- citations[
        citations$doi == x$doi,
        "cited_by_count",
        drop = TRUE
      ]
    } else {
      x$citations <- NA
    }
    return(x)
  })

# Sort elements by:
# 1. The order in which they appear in `top_pubs`
# 2. If absent from `top_pubs`, then year
publist <- publist[order(
    match(names(publist), top_pubs),
    purrr::map_int(publist, ~ as.integer(.x$year)),
    decreasing = c(FALSE, TRUE)
  )
]

formatted_publist <- publist |>
  purrr::map(format_and_highlight, group_members) |>
  purrr::map_chr(format_bibentry)

numbered_publist <- sprintf(
  '[%i] %s',
  seq_along(formatted_publist),
  formatted_publist
)

cat(numbered_publist, sep = "\n\n")
```

✷ indicates equal contributions <br>
✉ co-corresponding authorships
