---
title: "Internship position"
description: "Internship for bioinformatics trainers"
author: "Sarah Kaspar"
date: "2023-09-27"
categories: "Positions"
---

> Location: Heidelberg, Germany\
> Duration: 3 months\

## About the project 

The EMBL Data Science Centre is coordinating biodata activities across all EMBL sites. This includes offering high-quality internal and external training on computational methods with proven impact. The Data Science Centre is committed to open science principles and practices. Thus, one of our missions is to provide high-quality, publicly available materials. We are currently expanding our training offers with the aims of covering more topics in the area of biostatistics and scientific coding, and making existing materials applicable for self-learning and reusable by other trainers ([FAIR materials](https://www.fairsfair.eu/news/ten-simple-rules-making-training-materials-fair)).

We are offering a three months internship, where you can contribute to this effort in the area of biostatistics.


## Your role 

As part of our team, you can contribute to three specific areas:  

- Augment and FAIRify existing biostatistics training materials: This includes both creative tasks like writing text, and creating videos and illustrations, and technical tasks such as producing code and figures in R, compiling interactive online tutorials, and maintaining git repositories. 

- Develop new training materials: For this task you will collaborate with the respective experts at EMBL. This task is suitable for you, if you have a strong background in computational biology. We are open to your topic proposals.  

- Teaching: If you are interested in expanding your teaching experience (e.g. within internal courses or small informal sessions), you can use a diverse set of existing materials. If you develop materials during this internship, there are opportunities to teach those, too.  

The tasks can be adapted to your skills and learning objectives. 
For your application, please describe your background and the tasks you are most interested in.


## You have

- Solid understanding of undergraduate maths 
- Good writing and communication skills 
- Basic knowledge of (R) programming is an advantage 
- Motivation and ability to work independently 


## Why join us

What you can gain from this internship:  

- Practise your communication skills 
- Learn about biostatistical methods 
- Experience EMBL 
- Co-authorship on public training materials is possible 
- Renumeration: 450 Euro/month

## What else do I need to know

We are Europe’s flagship research laboratory for the life sciences – an intergovernmental organisation performing scientific research in disciplines including molecular biology, physics, chemistry and computer science. We are an international, innovative and interdisciplinary laboratory with more than 1600 employees from many nations, operating across six sites, in Heidelberg (HQ), Barcelona, Hinxton near Cambridge, Hamburg, Grenoble and Rome. Our mission is to offer vital services in training scientists, students and visitors at all levels; to develop new technologies and instruments in the life sciences, actively engage in technology transfer activities, and to integrate European life science research.


If you have any questions prior to your application for this position, please contact Sarah Kaspar (<sarah.kaspar@embl.de>).


 
