---
title: "Scientific writing advice"
description: "An eclectic and subjective list"
author: "Wolfgang Huber"
date: "2023-07-31"
categories: "Wisdom"
---

- Present experimental observations and measurements in past tense. Use present tense for presuppositions, interpretations and conclusions. The statements in past tense are the real, hard substance, the novelty of a research paper. 
- Use active voice. Avoid passive voice. Use the active voice form to make it clear what you did, what others did, or what already pre-existed from your previously reported work.
- Use one term per concept, and one concept per term. I.e., avoid lexical variation, as it adds unnecessary mental load on the reader (“Do they really mean the same? Or do they mean to leave room for some subtle distinction?”). Similarly, do not overload the same word with multiple meanings. A frequent mistake is using the same word for measured data, and for what the authors want them to mean. E.g., in RNA-seq, you may have collected a number of sequencing reads that match a certain target sequence, and want it to mean an mRNA abundance level. They are (hopefully) related. But they are not the same. It is part of the scientific approach to care about such distinctions. (Good scientists also know when it's fine to gloss over, so they can move on with the narrative rather than burdening everyone with pedantry.)
- In the Results section, focus on what you did. Musings about what you or someone could have done instead are (if at all) for Intro or Discussion. The Results section should proceed step by step. E.g., in an experimental omics paper, from sample acquisition, to choice of measurement technology, to specific protocol used, to specs of the data generated (e.g. number of reads, alignment, quality filters). Then, discuss how the data were analysed. Always step by step, and such that each intermediate step or result is explained before it is used by another step.
- In Intro and Discussion, find the right pitch for your story. Research happens at the boundary of the known and the unknown. Make sure you describe your situation in that position, i.e., what has been known, and what used to unknown but now is not, thanks to you. Make sure you find the right framing. It is rarely necessary to paint the scientific background starting with Darwin in the 1860s or the invention of digital computers, but it is also helpful to give a wide enough background for a target audience that has not been completely immersed in the topic for the last three years. 
- Be explicit and quantitative. Don't just say "few" or many" but state the number and/or the fraction quantitatively. Similarly, avoid most adjectives (e.g., "high", good", "efficient") and adverbs (e.g., "fast"). Instead, state the relevant physical quantities (e.g., speed, length, time interval) or numerical metrics (e.g., percent overlap, confusion table). In fact, adverbs and adjectives are rarely needed in Results and Methods sections of papers. There is some room for them in Intro and Discussion sections or reviews. (Scientific writing *is* different from writing prose.)
- Beware of dangling participles. Even if the intended meaning is clear. You may think you sound sophisticated, but it actually undermines you. Similarly for dangling pronouns.
- If you want to use fancy sounding words, make sure you really understand their meaning, and that it is what you want.
- Spell out abbreviations. You may think that you make the text more readable by compressing it, but the opposite is the case. Many readers do not read the paper linearly from beginning to end, and instead jump around or start in the middle. Even if you think a certain abbreviation is obvious, you will be surprised by how many readers you lose with it. 
- It's great to recall definitions of a scientific term, as a courtesy to the reader. Consult standard textbooks or at least Wikipedia before making up your own.
- Make each point once, and properly, and then move on. Avoid being repetitive. For instance, state the objective of the work, or of a particular portion of it, clearly and explicitly at the outset, and then just get on with describing the steps, and results; do not keep repeating the motives.
- Make sure there is logical progression. Avoid sounding circular. E.g., you can start a paragraph with stating a conclusion, and then provide your logical, fact-based argument for it, based on your premises and data. Or, start with the premises, and then go through the logical steps of data analysis to arrive at a conclusion. But do not put the conclusion, or the premises, both at the start and end of a paragraph. The reader will likely end up being puzzled about what was actually achieved.
- Use a spell-checker.
- Putting terms in quotes tends to look "unprofessional" and can in most cases be avoided by being careful about the choice of words.  
- If multiple spellings are possible for a term (e.g., hyphenation, capitalization), pick one and stick with it.
- In biomedical studies, use the word "patients" if you mean the actual people, i.e., human beings with life histories, families, feelings. Use another word if you are just referring to blood samples or tissue biopsies. 
- Don't say "X represents Y" when you just mean "X is Y". Doing so exposes you as careless of logical thinking.
- More generally, keep things simple and laconic. Overuse of buzzwords and technical jargon sounds pompous and undermines you.

### Figures:
- Colors are a great way of encoding a categorical or continuous variable in your data. Choose the color map carefully. There is good advice on this on the internet. If your paper has multiple plots mentioning the same variable, make sure the color map is the same. Similarly, as much as possible use different color maps for different variables.
- Font size: make sure all text in figures is large enough to be legible. Avoid clutter and repetition. Make choice of font, font style and sizes consistent across figure panels and figures. In practice, this is surprisingly hard.
- Aspect ratio: for plots in which $x$- and $y$-axis show the same physical or conceptual units, make sure the aspect ratio is consistent, i.e., usually 1:1.
