name: Deploy to S3 with Quarto

on:
  push: # Trigger workflow on pushes to the main branch
    branches:
      - optimise_workflow
  schedule: # Triggers on a weekly schedule (cron syntax)
    - cron: '0 8 * * 1'  # Every Monday at 08:00 UTC

jobs:
  run-in-container:
    runs-on: ubuntu-latest

    container: ghcr.io/miri-2000/docker_container:latest

    steps:
    # 1. Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # 2. Get the citation counts
    #- name: Run R script to get citation counts
    #  run: |
    #    sh -c "cd /project && Rscript rscripts/get_citation_counts.R"

    # 3. Renew the existing citation_counts.rds file
    - name: Commit and push changes if any
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"
        
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

        git add citation_counts.rds

        git commit -m "Automatic update of citation counts on $(date -I)" || echo "No changes to commit"

        git push -o ci.skip https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Huber-group-EMBL/Huber-group-EMBL.github.io.git HEAD:automated_branch || echo "No changes to commit"

    # 4. Prepare the citations
    - name: Run R script to prepare the citations
      run: |
        sh -c "cd /project && Rscript rscripts/prepare_citations.R"

    # 5. Make BBL
    - name: Make BBL
      run: |
        sh -c "cd /project && Rscript rscripts/makebbl.R"

    # 6. Create the page
    - name: Run R script to create the page
      run: |
        # Ensure necessary dependencies exist
        sh -c "cd /project && tth index"

        # Remove unnecessary files inside the container
        sh -c "cd /project && rm -f index.aux index.blg index.log index.out index.pdf lopcit.bib publ.rda index.bbl"

        # Run the R script inside the container
        sh -c "cd /project && Rscript rscripts/prochtml.R"

        # Remove the old index.html (if needed outside the container)
        rm -f index.html

    # 7. Render the Quarto project
    - name: Render Quarto project
      run: |
        R --version

        quarto render /project --cache-refresh

        ls -l _site

    # 8. Setup MinIO client
    - name: Setup MinIO client
      uses: lovellfelix/minio-deploy-action@v1

      with:
        endpoint: https://s3.embl.de/

        access_key: 4kRFKz352s8UbsA6Pycq

        secret_key: ${{ secrets.MINIO_SECRET_KEY }}

        bucket: 'www-huber'

        target_dir: '/group/'

        source_dir: '_site'

    # 9. Clean up Docker container
    - name: Clean up Docker container
      run: |
        docker stop quarto-container

        docker rm quarto-container